
# Lenient markdown rules (SEMBR-friendly, relaxed)
# First heading is a top-level heading
MD002: true

# Heading style (ATX is leading # symbols)
MD003:
  style: atx

# Unordered list symbol can be anything
MD004: false

# Unordered list indentation size
MD007:
  indent: 2

# Allow additional blank lines (SEMBR uses these for semantic breaks)
MD012: false

# Maximum line length (generous for prose)
MD013:
  line_length: 800
  tables: false

# Headings need blank lines before and after
MD022: true

# Duplicate headings are allowed
MD024: false

# Surround lists with blank lines
MD032: true

# Allow inline HTML
MD033: false

MD060:
  style: compact

